### ISSUE TITLE
googleMeasureR and loops

### ISSUE THREAD

**Issue by svmakarovv** [MarkEdmondson1234/googleMeasureR#2]
Hi.

I want to send user segments to GA. 

I have database like:

clientId1 segment1
clientID2 segment2
clientIdn segmentn

How can i send data via googleMeasureR?

It works:

`gmr_post(list(v=1,t="event",tid="UA-XXX",cid= "250597716.1510569333",ni=1,ec="test",ea="test",cd19=c"test"))`

But it doesn't:

`gmr_post(list(v=1,t="event",tid="UA-XXX",cid= c("250597716.1510569333","123"),ni=1,ec="test",ea="test",cd19=c("test","test2")))`

Is it possible to send data without loops?

Thanks.

**Comment by MarkEdmondson1234** [comment]
That would require batch hits which aren't implemented yet
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#batch-limitations

But even those only send 20 per hit.

**Comment by svmakarovv** [comment]
thanks for a quick reply)
yep, only send 20 per hit. But I have 500 000 rows. How do you think, is it ok for GA send 500k rows in one loop?

```
for (row in 1:nrow(dataframe)){
  gmr_post(data)
}
```

**Comment by MarkEdmondson1234** [comment]
There is no hit per second limit so it should be ok, it is afterall what is underpinning the normal GA javascript which copes with a lot more.  I guess R will be slow enough not to flood it.  

You may want to look at your timing arguments though, as they will all appear on one day otherwise.  You can only backdate them 28 hours I think.

**Comment by MarkEdmondson1234** [comment]
What exactly is your use case?  You may be better to use a custom data upload instead.

**Comment by svmakarovv** [comment]
I want send data about my users (segments) to GA for AdWords Remarketing list.
Custom data upload doesn't work correctly with remarketing:

_Users, who didn't visit the site in the 10 days prior to the data upload, will be added to remarking lists upon their next visit to the site_
https://developers.google.com/analytics/solutions/crm-integration

> You may want to look at your timing arguments though, as they will all appear on one day otherwise. You can only backdate them 28 hours I think.

Hmm, i use ni=1. I think it will prevent creating sessions and other problems with reporting.
