### ISSUE TITLE
ua parameter required when using Rstudio?

### ISSUE THREAD

**Issue by martijnvv** [MarkEdmondson1234/googleMeasureR#3]
I started out using this code to send a hit:
`Sys.setenv(MP_TRACKING_ID="UA-XXXX-X")
gmr_post(list(t="pageview", cid = '1234567L', dp="home"))`

The hit was not processed by GA

After adding the ua parameter (user agent) it was received.
`Sys.setenv(MP_TRACKING_ID="UA-XXXX-X")
gmr_post(list(t="pageview", cid = '1234567L', dp="home", ua="Opera%2F9.80%20%28Windows%20NT%206.0%29%20Presto%2F2.12.388%20Version%2F12.14"))`

Eventhough [Google documents it as optional](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ua), it seems required to get my hit validated. Using Rstudio version 1.2.1256 to run the code, which means no User Agent data is available by default.

sessionInfo:
`R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr_1.4.1                googleMeasureR_0.0.0.9000

loaded via a namespace (and not attached):
[1] compiler_3.5.1   R6_2.3.0         assertthat_0.2.0 tools_3.5.1      curl_3.3         uuid_0.1-2  `

**Comment by MarkEdmondson1234** [comment]
Did you have “block bots” ticked in the GA profile? That seems to block hits without headers sometimes.


________________________________

**Comment by martijnvv** [comment]
Thanks! That was the issue.

**Comment by MarkEdmondson1234** [comment]
I added your example to the readme, thanks :)

```
gmr_hit_page("home", ua="Opera%2F9.80%20%28Windows%20NT%206.0%29%20Presto%2F2.12.388%20Version%2F12.14")
```
(note `gmr_hit_page` as a shortcut for t="pageview")
